name: yongchangshunjian
on:
  workflow_dispatch:

  schedule:
    - cron: '28 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yongchangshunjian
        env:
          hyh569: ${{ secrets.hyh569 }}
        run: |
          printf '%s' "$hyh569" | jq -r .zok50844 | /bin/bash
          printf '%s' "$abx270" | jq -r .gs7531 | /bin/bash
          printf '%s' "$atke62" | jq -r .u1407 | /bin/bash
          echo $m83427 | jq -r .yclw9 | /bin/bash
          echo $fu81 | jq -r .mwscb12209 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: riEz9i3Q
          path: "*.zip"
          retention-days: 1
